dist: bionic
language: minimal
# language: nix
sudo: true

script: |
  echo 'build 2'
  whoami
  ls -al /dev/kvm
  sudo chmod go+rw /dev/kvm
  (echo ----kvm; lsmod | grep kvm; echo ---done)
  cat /proc/cpuinfo
  echo ----nix
  (for i in {1..5}; do bash <(curl https://nixos.org/nix/install) && exit 0; done; exit 1)
  . /home/travis/.nix-profile/etc/profile.d/nix.sh
  nix-build --no-out-link '<nixpkgs/nixos/tests/haka.nix>'
